# Generated by Django 5.2.17 on 2026-10-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
