# Generated by Django 5.2.17 on 2026-10-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_application_decided_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="decision_note",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="application_resumes/"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="seen_by_student",
            field=models.BooleanField(default=True),
        ),
    ]
