# Generated by Django 6.1.1 on 2026-09-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_company_password_remove_student_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume_filename',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
